package com.example.ui.analyzer.boot

object BootReportExporter {

    fun generateMarkdownReport(result: BootAnalysisResult): String {
        val sb = StringBuilder()
        sb.appendLine("# Boot & ROM Analysis Report")
        sb.appendLine("Generated by Galaxy J2 Prime Tool - Boot/ROM Analyzer Engine")
        sb.appendLine()

        // 1. Executive Summary
        sb.appendLine("## 1. Executive Summary")
        sb.appendLine("- **Last Confirmed Boot Stage**: `${result.lastConfirmedStage}`")
        sb.appendLine("- **Suspected Failure Stage**: `${result.suspectedFailureStage ?: "None"}` (Confidence: `${result.failureConfidence}`)")
        sb.appendLine("- **Total Identified Issues**: ${result.allIssues.size}")
        sb.appendLine()

        // 2. Boot Header
        sb.appendLine("## 2. Boot Image Header")
        if (result.bootHeader != null && result.bootHeader.isValid) {
            val h = result.bootHeader
            sb.appendLine("- **Header Version**: v${h.headerVersion}")
            sb.appendLine("- **Magic**: `${h.magic}`")
            sb.appendLine("- **Page Size**: ${h.pageSize} bytes")
            sb.appendLine("- **Header Size**: ${h.headerSize} bytes")
            sb.appendLine("- **Kernel Size**: ${h.kernelSize} bytes (Addr: 0x${h.kernelLoadAddr.toString(16)})")
            sb.appendLine("- **Ramdisk Size**: ${h.ramdiskSize} bytes (Addr: 0x${h.ramdiskLoadAddr.toString(16)})")
            sb.appendLine("- **OS Version**: ${h.osVersionString}")
            sb.appendLine("- **OS Patch Level**: ${h.osPatchLevelString}")
            sb.appendLine("- **Board Name**: ${h.boardName.ifEmpty { "N/A" }}")
            sb.appendLine("- **Cmdline**: `${h.cmdline.ifEmpty { "None" }}`")
        } else {
            sb.appendLine("No valid Android boot image header detected.")
        }
        sb.appendLine()

        // 3. Kernel
        sb.appendLine("## 3. Kernel Details")
        if (result.kernelInfo != null) {
            val k = result.kernelInfo
            sb.appendLine("- **Detected Format**: ${k.detectedFormat}")
            sb.appendLine("- **Architecture**: ${k.detectedArch}")
            sb.appendLine("- **Version**: ${k.kernelVersionString ?: "Unknown"}")
            sb.appendLine("- **Compiler**: ${k.compilerString ?: "Unknown"}")
            sb.appendLine("- **SMP Enabled**: ${k.isSmp}")
            sb.appendLine("- **Kernel Configs Found**: ${k.kernelConfigCount}")
        } else {
            sb.appendLine("Kernel payload not analyzed.")
        }
        sb.appendLine()

        // 4. Ramdisk
        sb.appendLine("## 4. Ramdisk")
        if (result.ramdiskInfo != null) {
            val r = result.ramdiskInfo
            sb.appendLine("- **Present**: ${r.present}")
            sb.appendLine("- **Compression**: ${r.compression}")
            sb.appendLine("- **CPIO Files Count**: ${r.cpioEntriesCount}")
            sb.appendLine("- **Key Files**: ${r.foundKeyFiles.joinToString(", ")}")
        } else {
            sb.appendLine("Ramdisk payload not present or not analyzed.")
        }
        sb.appendLine()

        // 5. Partition Map
        sb.appendLine("## 5. Partition Structure")
        if (result.partitionMap.isNotEmpty()) {
            sb.appendLine("| Partition | File | Size (Bytes) | Format |")
            sb.appendLine("|---|---|---|---|")
            for (p in result.partitionMap) {
                sb.appendLine("| `${p.partitionName}` | `${p.fileName}` | ${p.fileSize} | ${p.format} |")
            }
        } else {
            sb.appendLine("No partitions detected.")
        }
        sb.appendLine()

        // 6. Treble & A/B & Architecture
        sb.appendLine("## 6. Compatibility Indicators")
        sb.appendLine("- **Treble Enabled**: ${result.trebleInfo?.isTreble ?: "Unknown"}")
        sb.appendLine("- **A/B Slot Scheme**: ${result.abSlotInfo?.isAb ?: "Unknown"}")
        sb.appendLine("- **Overall Architecture**: ${result.architectureInfo?.overallArch ?: "Unknown"}")
        sb.appendLine()

        // 7. Boot Pipeline Status
        sb.appendLine("## 7. Boot Stage Progression")
        sb.appendLine("| Stage | Status | Summary |")
        sb.appendLine("|---|---|---|")
        for ((stage, res) in result.stageResults) {
            sb.appendLine("| **$stage** | `${res.status}` | ${res.summary} |")
        }
        sb.appendLine()

        // 8. Issues & Possible Causes
        sb.appendLine("## 8. Detected Issues & Potential Causes")
        if (result.allIssues.isNotEmpty()) {
            for (issue in result.allIssues) {
                sb.appendLine("### [${issue.severity}] ${issue.title}")
                sb.appendLine("- **Description**: ${issue.description}")
                sb.appendLine("- **Evidence**: `${issue.evidence}`")
                if (issue.file != null) sb.appendLine("- **File**: `${issue.file}`" + (if (issue.line != null) ":${issue.line}" else ""))
                if (issue.possibleCause != null) sb.appendLine("- **Possible Cause**: ${issue.possibleCause}")
                if (issue.recommendedFix != null) sb.appendLine("- **Recommended Fix**: ${issue.recommendedFix}")
                sb.appendLine()
            }
        } else {
            sb.appendLine("No blocking boot errors identified.")
        }
        sb.appendLine()

        // 9. Android 11 Porting Checks
        sb.appendLine("## 9. Android 11 Porting Checks")
        if (result.android11PortingChecks.isNotEmpty()) {
            for (check in result.android11PortingChecks) {
                sb.appendLine("- **[${check.status}] ${check.ruleName}**: ${check.description}")
                sb.appendLine("  - *Evidence*: `${check.evidence}`")
                if (check.recommendation != null) {
                    sb.appendLine("  - *Fix*: ${check.recommendation}")
                }
            }
        }
        sb.appendLine()

        // 10. Galaxy J2 Prime Hardware Profile
        if (result.j2PrimeProfile != null) {
            val j2 = result.j2PrimeProfile
            sb.appendLine("## 10. Galaxy J2 Prime (MT6737T) Profile Check")
            sb.appendLine("- **Expected**: Chipset: `${j2.expectedChipset}`, Arch: `${j2.expectedArch}`")
            sb.appendLine("- **Actual**: Chipset: `${j2.actualChipset}`, Arch: `${j2.actualArch}`")
            sb.appendLine("- **Profile Alignment**: ${if (j2.isMatch) "ALIGNED" else "MISMATCH / WARNING"}")
            for (n in j2.notes) {
                sb.appendLine("  - $n")
            }
        }

        return sb.toString()
    }

    fun generateJsonReport(result: BootAnalysisResult): String {
        val md = generateMarkdownReport(result)
        return """
        {
          "engine": "Galaxy J2 Prime Boot/ROM Analyzer",
          "lastConfirmedStage": "${result.lastConfirmedStage}",
          "suspectedFailureStage": "${result.suspectedFailureStage ?: "None"}",
          "failureConfidence": "${result.failureConfidence}",
          "issuesCount": ${result.allIssues.size},
          "isTreble": ${result.trebleInfo?.isTreble ?: false},
          "architecture": "${result.architectureInfo?.overallArch ?: "UNKNOWN"}",
          "markdownSummary": ${escapeJson(md)}
        }
        """.trimIndent()
    }

    private fun escapeJson(str: String): String {
        return "\"" + str.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\b", "\\b")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t") + "\""
    }
}
