package com.example.ui.analyzer.kernel.engine

import com.example.ui.analyzer.kernel.model.KernelCrashReport
import com.example.ui.analyzer.kernel.model.KernelSeverity

object KernelCrashExporter {

    fun toMarkdown(report: KernelCrashReport): String {
        val sb = StringBuilder()
        sb.appendLine("# Kernel Crash Analysis Report")
        sb.appendLine()
        sb.appendLine("**Generated by Galaxy J2 Prime Tool — Kernel Crash Analyzer**")
        sb.appendLine()

        // 1. File & Environment Metadata
        sb.appendLine("## 1. Environment & Source Information")
        sb.appendLine("| Property | Value |")
        sb.appendLine("|---|---|")
        sb.appendLine("| **File Name** | `${report.fileName}` |")
        sb.appendLine("| **File Size** | ${report.fileSize} bytes |")
        if (report.fileSha256 != null) {
            sb.appendLine("| **SHA-256** | `${report.fileSha256}` |")
        }
        sb.appendLine("| **Total Lines** | ${report.totalLinesAnalyzed} |")
        sb.appendLine("| **Kernel Release** | `${report.kernelVersion ?: "Unknown"}` |")
        sb.appendLine("| **Architecture** | `${report.architecture}` |")
        if (report.compilerInfo != null) {
            sb.appendLine("| **Compiler** | `${report.compilerInfo}` |")
        }
        if (report.buildDate != null) {
            sb.appendLine("| **Build Date** | ${report.buildDate} |")
        }
        sb.appendLine()

        // 2. Executive Summary
        sb.appendLine("## 2. Crash Summary")
        sb.appendLine("- **Total Crash Events Detected:** ${report.totalEvents}")
        sb.appendLine("- **Critical Faults (Panic / Oops / BUG):** ${report.criticalEvents}")
        sb.appendLine("- **Error Faults (Lockups / Watchdog / Hung Tasks):** ${report.errorEvents}")
        sb.appendLine("- **Warnings:** ${report.warningEvents}")
        sb.appendLine()

        // 3. Boot Failure Analysis
        val boot = report.bootFailureAnalysis
        if (boot.isBootFailureLikely) {
            sb.appendLine("## 3. Android Boot Failure Diagnostics")
            sb.appendLine("> ⚠️ **Potential Boot Failure / Bootloop Detected**")
            sb.appendLine()
            if (boot.detectedBlockers.isNotEmpty()) {
                sb.appendLine("### Detected Boot Blockers:")
                boot.detectedBlockers.forEach { sb.appendLine("- 🛑 $it") }
                sb.appendLine()
            }
            if (boot.recoveryRecommendations.isNotEmpty()) {
                sb.appendLine("### Recommended Fixes:")
                boot.recoveryRecommendations.forEach { sb.appendLine("- 💡 $it") }
                sb.appendLine()
            }
        }

        // 4. Suspected Subsystems
        if (report.suspectedSubsystems.isNotEmpty()) {
            sb.appendLine("## 4. Suspected Subsystems")
            report.suspectedSubsystems.forEach { sub ->
                sb.appendLine("- **${sub.type.displayName}** (Confidence: `${sub.confidence}`)")
                sb.appendLine("  - *Matched Evidence Keywords:* `${sub.matchedKeywords.joinToString(", ")}`")
            }
            sb.appendLine()
        }

        // 5. Critical Crash Events & Root Cause
        sb.appendLine("## 5. Detected Crash Events (${report.crashEvents.size})")
        report.crashEvents.forEachIndexed { index, ev ->
            sb.appendLine("### Crash #${index + 1}: ${ev.type.displayName} [${ev.severity}]")
            sb.appendLine("- **Timestamp:** `${ev.timestamp ?: "N/A"}` (Line ${ev.sourceLineIndex})")
            if (ev.cpu != null) sb.appendLine("- **CPU:** #${ev.cpu}")
            if (ev.pid != null) sb.appendLine("- **PID:** ${ev.pid} (Comm: `${ev.comm ?: "unknown"}`)")
            if (ev.faultAddress != null) sb.appendLine("- **Fault Address:** `${ev.faultAddress}`")
            if (ev.panicReason != null) sb.appendLine("- **Reason:** `${ev.panicReason}`")

            // Analysis
            ev.analysis?.let { ana ->
                sb.appendLine()
                sb.appendLine("#### Root Cause Deduction:")
                sb.appendLine("- **Fact:** ${ana.fact}")
                if (ana.evidenceList.isNotEmpty()) {
                    sb.appendLine("- **Evidence:**")
                    ana.evidenceList.forEach { evItem -> sb.appendLine("  - $evItem") }
                }
                if (ana.possibleCauses.isNotEmpty()) {
                    sb.appendLine("- **Possible Cause(s):** (Confidence: `${ana.confidence}`)")
                    ana.possibleCauses.forEach { cause -> sb.appendLine("  - $cause") }
                }
                if (ana.recommendedActions.isNotEmpty()) {
                    sb.appendLine("- **Recommended Actions:**")
                    ana.recommendedActions.forEach { act -> sb.appendLine("  - $act") }
                }
            }

            // Call Trace
            if (ev.stackFrames.isNotEmpty()) {
                sb.appendLine()
                sb.appendLine("#### Call Trace:")
                sb.appendLine("```text")
                ev.stackFrames.forEach { frame ->
                    sb.appendLine(frame.formattedDisplay)
                }
                sb.appendLine("```")
            }

            // Registers
            if (!ev.registers.isEmpty) {
                sb.appendLine()
                sb.appendLine("#### Registers (${ev.registers.architecture}):")
                sb.appendLine("```text")
                if (ev.registers.pc != null) sb.appendLine("PC: ${ev.registers.pc}")
                if (ev.registers.lr != null) sb.appendLine("LR: ${ev.registers.lr}")
                if (ev.registers.sp != null) sb.appendLine("SP: ${ev.registers.sp}")
                if (ev.registers.cpsr != null) sb.appendLine("CPSR: ${ev.registers.cpsr}")
                if (ev.registers.esr != null) sb.appendLine("ESR: ${ev.registers.esr}")
                if (ev.registers.far != null) sb.appendLine("FAR: ${ev.registers.far}")
                ev.registers.registers.forEach { (k, v) ->
                    sb.appendLine("$k: $v")
                }
                sb.appendLine("```")
            }
            sb.appendLine("---")
            sb.appendLine()
        }

        // 6. Repeated Call Traces
        if (report.repeatedTraces.isNotEmpty()) {
            sb.appendLine("## 6. Call Trace Signature Grouping")
            report.repeatedTraces.forEach { grp ->
                sb.appendLine("- **Occurrences:** ${grp.occurrences}x | **Signature:** `${grp.signature}`")
                sb.appendLine("  - *First:* `${grp.firstTimestamp ?: "N/A"}` | *Last:* `${grp.lastTimestamp ?: "N/A"}`")
            }
            sb.appendLine()
        }

        return sb.toString()
    }

    fun toPlainText(report: KernelCrashReport): String {
        val sb = StringBuilder()
        sb.appendLine("=== KERNEL CRASH ANALYSIS REPORT ===")
        sb.appendLine("File: ${report.fileName} (${report.fileSize} bytes)")
        sb.appendLine("SHA-256: ${report.fileSha256 ?: "N/A"}")
        sb.appendLine("Kernel: ${report.kernelVersion ?: "Unknown"} [${report.architecture}]")
        sb.appendLine("Total Events: ${report.totalEvents} (Critical: ${report.criticalEvents}, Error: ${report.errorEvents}, Warnings: ${report.warningEvents})")
        sb.appendLine()

        if (report.bootFailureAnalysis.isBootFailureLikely) {
            sb.appendLine("--- BOOT FAILURE DIAGNOSIS ---")
            report.bootFailureAnalysis.detectedBlockers.forEach { sb.appendLine("  BLOCKER: $it") }
            report.bootFailureAnalysis.recoveryRecommendations.forEach { sb.appendLine("  FIX: $it") }
            sb.appendLine()
        }

        report.crashEvents.forEachIndexed { i, ev ->
            sb.appendLine("--- EVENT #${i + 1}: ${ev.type.displayName} [${ev.severity}] ---")
            sb.appendLine("Timestamp: ${ev.timestamp ?: "N/A"} | CPU: ${ev.cpu ?: -1} | PID: ${ev.pid ?: -1} | Comm: ${ev.comm ?: "unknown"}")
            if (ev.faultAddress != null) sb.appendLine("Fault Address: ${ev.faultAddress}")
            if (ev.panicReason != null) sb.appendLine("Reason: ${ev.panicReason}")
            if (ev.analysis != null) {
                sb.appendLine("Fact: ${ev.analysis.fact}")
                ev.analysis.possibleCauses.forEach { sb.appendLine("Possible Cause (${ev.analysis.confidence}): $it") }
            }
            if (ev.stackFrames.isNotEmpty()) {
                sb.appendLine("Stack Trace:")
                ev.stackFrames.forEach { sb.appendLine("  ${it.formattedDisplay}") }
            }
            sb.appendLine()
        }

        return sb.toString()
    }

    fun toJson(report: KernelCrashReport): String {
        // Lightweight manual JSON serialization without heavy external reflection
        val sb = StringBuilder()
        sb.append("{\n")
        sb.append("  \"fileName\": \"${escapeJson(report.fileName)}\",\n")
        sb.append("  \"fileSize\": ${report.fileSize},\n")
        sb.append("  \"sha256\": \"${report.fileSha256 ?: ""}\",\n")
        sb.append("  \"kernelVersion\": \"${escapeJson(report.kernelVersion ?: "")}\",\n")
        sb.append("  \"architecture\": \"${report.architecture}\",\n")
        sb.append("  \"totalEvents\": ${report.totalEvents},\n")
        sb.append("  \"criticalEvents\": ${report.criticalEvents},\n")
        sb.append("  \"errorEvents\": ${report.errorEvents},\n")
        sb.append("  \"warningEvents\": ${report.warningEvents},\n")
        sb.append("  \"bootFailure\": {\n")
        sb.append("    \"isLikely\": ${report.bootFailureAnalysis.isBootFailureLikely},\n")
        sb.append("    \"blockers\": [${report.bootFailureAnalysis.detectedBlockers.joinToString(",") { "\"${escapeJson(it)}\"" }}]\n")
        sb.append("  },\n")
        sb.append("  \"crashEvents\": [\n")
        val eventsJson = report.crashEvents.joinToString(",\n") { ev ->
            val framesJson = ev.stackFrames.joinToString(",") { f ->
                "{\"idx\":${f.frameIndex},\"symbol\":\"${escapeJson(f.symbol ?: "")}\",\"addr\":\"${f.address ?: ""}\",\"offset\":\"${f.offsetHex ?: ""}\"}"
            }
            """    {
      "id": "${ev.id}",
      "type": "${ev.type.name}",
      "severity": "${ev.severity.name}",
      "timestamp": "${ev.timestamp ?: ""}",
      "cpu": ${ev.cpu ?: -1},
      "pid": ${ev.pid ?: -1},
      "comm": "${escapeJson(ev.comm ?: "")}",
      "faultAddress": "${ev.faultAddress ?: ""}",
      "reason": "${escapeJson(ev.panicReason ?: "")}",
      "stackFrames": [$framesJson]
    }"""
        }
        sb.append(eventsJson)
        sb.append("\n  ]\n}")
        return sb.toString()
    }

    private fun escapeJson(str: String): String {
        return str.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
    }
}
